import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";



const myFont = localFont({
  src: "../../public/font/Sansation_Regular.ttf", // Path relative to the public directory
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
